version: '3.8'

services:
  progress_bar_app:
    container_name: progress_app
    build:
      context: .
      dockerfile: Dockerfile
    command:  bash -c 'chmod +x ./server_config/setup.sh && ./server_config/setup.sh'
    ports:
      - 8001:90
    volumes:
      - .:/progress_app
    extra_hosts:
      - "host.docker.internal:host-gateway"


    
    
